-- 코드를 입력하세요
SELECT *  
FROM (SELECT CAR_ID, CAR_TYPE, (DAILY_FEE*30*(100-DISCOUNT_RATE)/100) FEE
    FROM CAR_RENTAL_COMPANY_CAR 
    INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
    USING(CAR_TYPE)
    WHERE (CAR_TYPE = '세단' OR CAR_TYPE = 'SUV' )
    AND DURATION_TYPE ='30일 이상'
    )
WHERE CAR_ID NOT IN (SELECT DISTINCT CAR_ID
                    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
                    WHERE END_DATE >= TO_DATE('2022-11-01', 'YYYY-mm-dd')
                    AND START_DATE <= TO_DATE('2022-11-30', 'YYYY-mm-dd')
                    )
AND FEE >= 500000 AND  FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC