-- 코드를 입력하세요
WITH SALE AS (
    SELECT BOOK_ID, SALES_DATE, SALES
    FROM BOOK_SALES 
    WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
    )

SELECT B.CATEGORY, SUM(S.SALES) TOTAL_SALES
    FROM SALE S
         INNER JOIN BOOK B
         ON (B.BOOK_ID = S.BOOK_ID)
         GROUP BY CATEGORY
         ORDER BY CATEGORY ASC;

