-- 코드를 입력하세요
WITH RECURSIVE TIME AS(
    SELECT 0 AS H
    UNION ALL
    SELECT H + 1 FROM TIME WHERE H < 23 )

SELECT H HOUR, 0
    FROM TIME 
    WHERE H NOT IN (SELECT HOUR(DATETIME) HOUR
                   FROM ANIMAL_OUTS 
                   GROUP BY HOUR )
UNION ALL

SELECT HOUR(DATETIME) HOUR, COUNT(ANIMAL_ID) "COUNT"
    FROM ANIMAL_OUTS
    GROUP BY HOUR
    ORDER BY HOUR;