-- 코드를 입력하세요
SELECT '/home/grep/src/' || A.BOARD_ID || '/' || B.FILE_ID || B.FILE_NAME || B.FILE_EXT as FILE_PATH
FROM USED_GOODS_BOARD A, USED_GOODS_FILE B
WHERE A.BOARD_ID = B.BOARD_ID
AND A.VIEWS = (SELECT MAX(VIEWS)
               FROM USED_GOODS_BOARD
              )
AND 1=1
ORDER BY FILE_ID DESC