-- 코드를 입력하세요
SELECT C.HOUR,count(H.HOUR) AS "COUNT"
FROM (SELECT to_char(DATETIME,'HH24') HOUR FROM ANIMAL_OUTS ) H,
     (SELECT LEVEL-1 HOUR FROM DUAL CONNECT BY LEVEL <= 24) C
WHERE C.HOUR=H.HOUR(+)
GROUP BY C.HOUR
ORDER BY C.HOUR
