-- 코드를 입력하세요
WITH OCT AS (
    SELECT CAR_ID, MONTH(START_DATE) AS "MONTH", COUNT(*) AS "RECORDS"
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID, MONTH
), FIVE AS(
    SELECT CAR_ID, COUNT(*) AS "TOTAL_RECORDS"
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
)

SELECT O.MONTH, O.CAR_ID, O.RECORDS
    FROM OCT O
    INNER JOIN FIVE F
    ON O.CAR_ID = F.CAR_ID
    ORDER BY O.MONTH ASC, F.CAR_ID DESC;