-- 코드를 입력하세요
SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(S.SALES * B.PRICE) TOTAL_SALES
FROM BOOK B, AUTHOR A, BOOK_SALES S
WHERE B.AUTHOR_ID =A.AUTHOR_ID
AND B.BOOK_ID = S.BOOK_ID
AND TO_CHAR(S.SALES_DATE, 'YYYYmm') = '202201'
GROUP BY B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
ORDER BY B.AUTHOR_ID, B.CATEGORY DESC