-- 코드를 입력하세요
SELECT E.HISTORY_ID
     , ROUND((CRCC.DAILY_FEE - (CRCC.DAILY_FEE * NVL(E.DISCOUNT_RATE, 0) / 100)) * DURATION_DATE, 1) AS FEE
  FROM CAR_RENTAL_COMPANY_CAR CRCC
  JOIN (
        SELECT CRCRH.HISTORY_ID
             , CRCRH.CAR_ID
             , (CRCRH.END_DATE - CRCRH.START_DATE + 1) AS DURATION_DATE
             , MAX(D.DURATION_TYPE) AS DURATION_TYPE
             , MAX(D.DISCOUNT_RATE) AS DISCOUNT_RATE
          FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCRH
          LEFT JOIN (
                   SELECT TO_NUMBER(REGEXP_REPLACE(DURATION_TYPE, '[^0-9]')) AS DURATION_TYPE
                        , DISCOUNT_RATE
                        , CAR_TYPE
                     FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
                    WHERE CAR_TYPE = '트럭'
          ) D ON (CRCRH.END_DATE - CRCRH.START_DATE + 1) >= D.DURATION_TYPE
         GROUP BY CRCRH.HISTORY_ID
                , CRCRH.CAR_ID
                , CRCRH.END_DATE - CRCRH.START_DATE
 ) E ON CRCC.CAR_ID = E.CAR_ID 
 WHERE CRCC.CAR_TYPE = '트럭'
 ORDER BY FEE DESC, E.HISTORY_ID DESC