-- 코드를 입력하세요
-- 2022.01 도서 판매 데이터를 기준으로
-- 저자 별, 카테고리 별 매출액 ( 판매량 * 판매가 )
-- 저자 ID, 저자명, 카테고리, 매출액 리스트 출력 
-- 저자 ID 오름차순, 카테고리 내림차순 
WITH JAN_SALES AS (
    SELECT BOOK_ID, SUM(SALES) AS SALES
    FROM BOOK_SALES 
    WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
    GROUP BY BOOK_ID
    )

SELECT B.AUTHOR_ID, A.AUTHOR_NAME ,B.CATEGORY, SUM(B.PRICE * J.SALES) AS "TOTAL_SALES"
    FROM JAN_SALES J 
    INNER JOIN BOOK B ON J.BOOK_ID = B.BOOK_ID
    INNER JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
    GROUP BY B.AUTHOR_ID, B.CATEGORY, A.AUTHOR_NAME
    ORDER BY A.AUTHOR_ID ASC, B.CATEGORY DESC;
    