-- 코드를 입력하세요
WITH MISS AS
(SELECT ANIMAL_ID, NAME, DATETIME
 FROM ANIMAL_OUTS)

SELECT A.ANIMAL_ID ,A.NAME
FROM MISS M INNER JOIN ANIMAL_INS A
ON A.ANIMAL_ID = M.ANIMAL_ID
WHERE A.DATETIME > M.DATETIME
ORDER BY A.DATETIME