-- 코드를 입력하세요
SELECT MAX(ROWNUM) AS USERS
FROM (SELECT ROWNUM, USER_ID
     FROM USER_INFO
     WHERE AGE BETWEEN 20 AND 29
     AND JOINED BETWEEN TO_DATE(20210101, 'YYYY-MM-DD') AND TO_DATE(20211231, 'YYYY-MM-DD') 
    )
    
